#!/bin/sh
set -e

case "$1" in
    configure)
        uuidgen > /var/lib/tealinux-software-center/uuid
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p tealinux-software-center /usr/share/tealinux-software-center
fi

# End automatically added section



